export const years = [
  { value: "2024", label: "2024" },
  { value: "2023", label: "2023" },
  { value: "2022", label: "2022" },
  { value: "2021", label: "2021" },
  { value: "2020", label: "2020" },
  { value: "2019", label: "2019" },
  { value: "2018", label: "2018" },
  { value: "2017", label: "2017" },
  { value: "2016", label: "2016" },
  { value: "2015", label: "2015" },
  { value: "2014", label: "2014" },
  { value: "2013", label: "2013" },
  { value: "2012", label: "2012" },
  { value: "2011", label: "2011" },
  { value: "2010", label: "2010" },
  { value: "2009", label: "2009" },
  { value: "2008", label: "2008" },
  { value: "2007", label: "2007" },
  { value: "2006", label: "2006" },
  { value: "2005", label: "2005" },
  { value: "2004", label: "2004" },
  { value: "2003", label: "2003" },
  { value: "2002", label: "2002" },
  { value: "2001", label: "2001" },
  { value: "2000", label: "2000" },
];

export const vehicleMakes = [
  { value: "Toyota", label: "Toyota" },
  { value: "Honda", label: "Honda" },
  { value: "Ford", label: "Ford" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Nissan", label: "Nissan" },
  { value: "BMW", label: "BMW" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Kia", label: "Kia" },
];

export const vehicleModels = {
  Toyota: [
    { value: "Camry", label: "Camry" },
    { value: "Corolla", label: "Corolla" },
    { value: "RAV4", label: "RAV4" },
    { value: "Highlander", label: "Highlander" },
    { value: "Tacoma", label: "Tacoma" },
  ],
  Honda: [
    { value: "Civic", label: "Civic" },
    { value: "Accord", label: "Accord" },
    { value: "CR-V", label: "CR-V" },
    { value: "Pilot", label: "Pilot" },
    { value: "Odyssey", label: "Odyssey" },
  ],
  Ford: [
    { value: "F-150", label: "F-150" },
    { value: "Escape", label: "Escape" },
    { value: "Explorer", label: "Explorer" },
    { value: "Mustang", label: "Mustang" },
    { value: "Edge", label: "Edge" },
  ],
  Chevrolet: [
    { value: "Silverado", label: "Silverado" },
    { value: "Equinox", label: "Equinox" },
    { value: "Malibu", label: "Malibu" },
    { value: "Tahoe", label: "Tahoe" },
    { value: "Traverse", label: "Traverse" },
  ],
  Nissan: [
    { value: "Altima", label: "Altima" },
    { value: "Sentra", label: "Sentra" },
    { value: "Rogue", label: "Rogue" },
    { value: "Pathfinder", label: "Pathfinder" },
    { value: "Frontier", label: "Frontier" },
  ],
  BMW: [
    { value: "3 Series", label: "3 Series" },
    { value: "5 Series", label: "5 Series" },
    { value: "X3", label: "X3" },
    { value: "X5", label: "X5" },
    { value: "7 Series", label: "7 Series" },
  ],
  "Mercedes-Benz": [
    { value: "C-Class", label: "C-Class" },
    { value: "E-Class", label: "E-Class" },
    { value: "GLC", label: "GLC" },
    { value: "GLE", label: "GLE" },
    { value: "S-Class", label: "S-Class" },
  ],
  Volkswagen: [
    { value: "Jetta", label: "Jetta" },
    { value: "Passat", label: "Passat" },
    { value: "Tiguan", label: "Tiguan" },
    { value: "Atlas", label: "Atlas" },
    { value: "Golf", label: "Golf" },
  ],
  Hyundai: [
    { value: "Elantra", label: "Elantra" },
    { value: "Sonata", label: "Sonata" },
    { value: "Tucson", label: "Tucson" },
    { value: "Santa Fe", label: "Santa Fe" },
    { value: "Palisade", label: "Palisade" },
  ],
  Kia: [
    { value: "Soul", label: "Soul" },
    { value: "Sportage", label: "Sportage" },
    { value: "Sorento", label: "Sorento" },
    { value: "Optima", label: "Optima" },
    { value: "Telluride", label: "Telluride" },
  ],
};

export const vehicleTypes = [
  { value: "Sedan", label: "Sedan" },
  { value: "SUV", label: "SUV" },
  { value: "Truck", label: "Truck" },
  { value: "Coupe", label: "Coupe" },
  { value: "Hatchback", label: "Hatchback" },
  { value: "Convertible", label: "Convertible" },
  { value: "Minivan", label: "Minivan" },
  { value: "Wagon", label: "Wagon" },
  { value: "Crossover", label: "Crossover" },
  { value: "Electric", label: "Electric" },
];
