import { Figtree } from "next/font/google";
import { DashboardWrapper } from "@/components/DashboardWrapper";
import type { Metadata } from "next";
import "./globals.css";

const figtreeSans = Figtree({
  variable: "--font-figtree",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={figtreeSans.variable}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
